import ArgumentParser
import Foundation
import LaTeXToolsCore

struct ExportCommand: ParsableCommand {
  static let configuration = CommandConfiguration(
    commandName: "export",
    abstract: "Write a Makefile that forwards build and clean to latextools.",
    aliases: ["generate"]
  )

  mutating func run() throws {
    try run(in: CommandContext())
  }

  func run(in context: CommandContext) throws {
    let project = try context.findProject()
    try BuildEngine(runner: context.runner).validate(project)
    let makefile = project.rootURL.appendingPathComponent("Makefile")

    try
      "# Generated by latextools\n\n.PHONY: all clean\nall:\n\tlatextools build\n\nclean:\n\tlatextools clean\n"
      .write(to: makefile, atomically: true, encoding: .utf8)

    context.output("Wrote \(makefile.path)")
  }
}
