name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        # On Windows, swift test is stuck after build completes.
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: '6.4'
          development: true
      - name: Test
        run: swift test
